# Generated by Django 4.2.16 on 2024-10-18 11:56

from django.db import migrations, models

import api.auth.common.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[
                 api.auth.common.models.EmailValidator()], verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'taxomap_users',
                'managed': True,
            },
        ),
    ]
