# Generated by Django 4.2.10 on 2024-02-27 08:06

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marmot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField()),
                ('last_known_position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('birth_date', models.DateTimeField()),
                ('weight', models.FloatField(null=True)),
                ('read_only_field', models.CharField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
