# Generated by Django 4.2.10 on 2024-06-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otter',
            fields=[
                ('entity_version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('bath_time', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
