create table country(
    code char(2) primary key,
    name_ca text not null,
    name_en text not null,
    name_es text not null
);

insert into country(name_ca, name_en, name_es, code) values ('Andorra', 'Andorra', 'Andorra', 'AD');
insert into country(name_ca, name_en, name_es, code) values ('Emirats Àrabs Units, els', 'United Arab Emirates', 'Emiratos Árabes Unidos', 'AE');
insert into country(name_ca, name_en, name_es, code) values ('Afganistan', 'Afghanistan', 'Afganistán', 'AF');
insert into country(name_ca, name_en, name_es, code) values ('Antigua i Barbuda', 'Antigua and Barbuda', 'Antigua y Barbuda', 'AG');
insert into country(name_ca, name_en, name_es, code) values ('Anguilla', 'Anguilla', 'Anguilla', 'AI');
insert into country(name_ca, name_en, name_es, code) values ('Albània', 'Albania', 'Albania', 'AL');
insert into country(name_ca, name_en, name_es, code) values ('Armènia', 'Armenia', 'Armenia', 'AM');
insert into country(name_ca, name_en, name_es, code) values ('Angola', 'Angola', 'Angola', 'AO');
insert into country(name_ca, name_en, name_es, code) values ('Antàrtida', 'Antarctica', 'Antártida', 'AQ');
insert into country(name_ca, name_en, name_es, code) values ('Argentina', 'Argentina', 'Argentina', 'AR');
insert into country(name_ca, name_en, name_es, code) values ('Samoa Americana', 'American Samoa', 'Samoa Americana', 'AS');
insert into country(name_ca, name_en, name_es, code) values ('Àustria', 'Austria', 'Austria', 'AT');
insert into country(name_ca, name_en, name_es, code) values ('Austràlia', 'Australia', 'Australia', 'AU');
insert into country(name_ca, name_en, name_es, code) values ('Aruba', 'Aruba', 'Aruba', 'AW');
insert into country(name_ca, name_en, name_es, code) values ('Aland', 'Åland Islands', 'Åland', 'AX');
insert into country(name_ca, name_en, name_es, code) values ('Azerbaidjan', 'Azerbaijan', 'Azerbaiyán', 'AZ');
insert into country(name_ca, name_en, name_es, code) values ('Bòsnia i Hercegovina', 'Bosnia and Herzegovina', 'Bosnia y Herzegovina', 'BA');
insert into country(name_ca, name_en, name_es, code) values ('Barbados', 'Barbados', 'Barbados', 'BB');
insert into country(name_ca, name_en, name_es, code) values ('Bangladesh', 'Bangladesh', 'Bangladés', 'BD');
insert into country(name_ca, name_en, name_es, code) values ('Bèlgica', 'Belgium', 'Bélgica', 'BE');
insert into country(name_ca, name_en, name_es, code) values ('Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'BF');
insert into country(name_ca, name_en, name_es, code) values ('Bulgària', 'Bulgaria', 'Bulgaria', 'BG');
insert into country(name_ca, name_en, name_es, code) values ('Bahrain', 'Bahrain', 'Baréin', 'BH');
insert into country(name_ca, name_en, name_es, code) values ('Burundi', 'Burundi', 'Burundi', 'BI');
insert into country(name_ca, name_en, name_es, code) values ('Benín', 'Benin', 'Benin', 'BJ');
insert into country(name_ca, name_en, name_es, code) values ('Saint-Barthélemy', 'Saint Barthélemy', 'San Bartolomé', 'BL');
insert into country(name_ca, name_en, name_es, code) values ('Bermudes', 'Bermuda', 'Bermuda', 'BM');
insert into country(name_ca, name_en, name_es, code) values ('Brunei', 'Brunei', 'Brunéi', 'BN');
insert into country(name_ca, name_en, name_es, code) values ('Bolívia', 'Bolivia', 'Bolivia', 'BO');
insert into country(name_ca, name_en, name_es, code) values ('Bonaire, Sint Eustatius i Saba', 'Bonaire, Sint Eustatius and Saba', 'Bonaire, San Eustaquio y Saba', 'BQ');
insert into country(name_ca, name_en, name_es, code) values ('Brasil', 'Brazil', 'Brasil', 'BR');
insert into country(name_ca, name_en, name_es, code) values ('Bahames, les', 'Bahamas', 'Bahamas', 'BS');
insert into country(name_ca, name_en, name_es, code) values ('Bhutan', 'Bhutan', 'Bután', 'BT');
insert into country(name_ca, name_en, name_es, code) values ('Illa Bouvet', 'Bouvet Island', 'Isla Bouvet', 'BV');
insert into country(name_ca, name_en, name_es, code) values ('Botswana', 'Botswana', 'Botswana', 'BW');
insert into country(name_ca, name_en, name_es, code) values ('Belarús', 'Belarus', 'Bielorrusia', 'BY');
insert into country(name_ca, name_en, name_es, code) values ('Belize', 'Belize', 'Belice', 'BZ');
insert into country(name_ca, name_en, name_es, code) values ('Canadà', 'Canada', 'Canadá', 'CA');
insert into country(name_ca, name_en, name_es, code) values ('Illes Cocos (Keeling)', 'Cocos (Keeling) Islands', 'Islas Cocos', 'CC');
insert into country(name_ca, name_en, name_es, code) values ('República Democràtica del Congo', 'Congo, the Democratic Republic of the', 'República Democrática del Congo', 'CD');
insert into country(name_ca, name_en, name_es, code) values ('República Centreafricana', 'Central African Republic', 'Republica Centroafricana', 'CF');
insert into country(name_ca, name_en, name_es, code) values ('Congo', 'Congo', 'Congo', 'CG');
insert into country(name_ca, name_en, name_es, code) values ('Suïssa', 'Switzerland', 'Suiza', 'CH');
insert into country(name_ca, name_en, name_es, code) values ('Costa d''Ivori', 'Côte d''Ivoire', 'Costa de Marfil', 'CI');
insert into country(name_ca, name_en, name_es, code) values ('Illes Cook', 'Cook Islands', 'Islas Cook', 'CK');
insert into country(name_ca, name_en, name_es, code) values ('Xile', 'Chile', 'Chile', 'CL');
insert into country(name_ca, name_en, name_es, code) values ('Camerun', 'Cameroon', 'Camerún', 'CM');
insert into country(name_ca, name_en, name_es, code) values ('Xina', 'China', 'China', 'CN');
insert into country(name_ca, name_en, name_es, code) values ('Colòmbia', 'Colombia', 'Colombia', 'CO');
insert into country(name_ca, name_en, name_es, code) values ('Costa Rica', 'Costa Rica', 'Costa Rica', 'CR');
insert into country(name_ca, name_en, name_es, code) values ('Cuba', 'Cuba', 'Cuba', 'CU');
insert into country(name_ca, name_en, name_es, code) values ('Cap Verd', 'Cape Verde', 'Cabo Verde', 'CV');
insert into country(name_ca, name_en, name_es, code) values ('Curaçao', 'Curaçao', 'Curazao', 'CW');
insert into country(name_ca, name_en, name_es, code) values ('Illa Christmas', 'Christmas Island', 'Isla de Navidad', 'CX');
insert into country(name_ca, name_en, name_es, code) values ('Xipre', 'Cyprus', 'Chipre', 'CY');
insert into country(name_ca, name_en, name_es, code) values ('Txèquia', 'Czech Republic', 'República Checa', 'CZ');
insert into country(name_ca, name_en, name_es, code) values ('Alemanya', 'Germany', 'Alemania', 'DE');
insert into country(name_ca, name_en, name_es, code) values ('Djibouti', 'Djibouti', 'Yibuti', 'DJ');
insert into country(name_ca, name_en, name_es, code) values ('Dinamarca', 'Denmark', 'Dinamarca', 'DK');
insert into country(name_ca, name_en, name_es, code) values ('Dominica', 'Dominica', 'Dominica', 'DM');
insert into country(name_ca, name_en, name_es, code) values ('República Dominicana', 'Dominican Republic', 'República Dominicana', 'DO');
insert into country(name_ca, name_en, name_es, code) values ('Algèria', 'Algeria', 'Argelia', 'DZ');
insert into country(name_ca, name_en, name_es, code) values ('Equador', 'Ecuador', 'Ecuador', 'EC');
insert into country(name_ca, name_en, name_es, code) values ('Estònia', 'Estonia', 'Estonia', 'EE');
insert into country(name_ca, name_en, name_es, code) values ('Egipte', 'Egypt', 'Egipto', 'EG');
insert into country(name_ca, name_en, name_es, code) values ('Sàhara Occidental', 'Western Sahara', 'Sahara Occcidental', 'EH');
insert into country(name_ca, name_en, name_es, code) values ('Eritrea', 'Eritrea', 'Eritrea', 'ER');
insert into country(name_ca, name_en, name_es, code) values ('Espanya', 'Spain', 'España', 'ES');
insert into country(name_ca, name_en, name_es, code) values ('Etiòpia', 'Ethiopia', 'Etiopía', 'ET');
insert into country(name_ca, name_en, name_es, code) values ('Finlàndia', 'Finland', 'Finlandia', 'FI');
insert into country(name_ca, name_en, name_es, code) values ('Fiji', 'Fiji', 'Fiyi', 'FJ');
insert into country(name_ca, name_en, name_es, code) values ('Illes Falkland (Malvines)', 'Falkland Islands (Malvinas)', 'Islas Malvinas', 'FK');
insert into country(name_ca, name_en, name_es, code) values ('Micronèsia', 'Micronesia, Federated States of', 'Micronesia', 'FM');
insert into country(name_ca, name_en, name_es, code) values ('Fèroe', 'Faroe Islands', 'Islas Feroe', 'FO');
insert into country(name_ca, name_en, name_es, code) values ('França', 'France', 'Francia', 'FR');
insert into country(name_ca, name_en, name_es, code) values ('Gabon', 'Gabon', 'Gabón', 'GA');
insert into country(name_ca, name_en, name_es, code) values ('Regne Unit', 'United Kingdom', 'Reino Unido', 'GB');
insert into country(name_ca, name_en, name_es, code) values ('Grenada', 'Grenada', 'Granada', 'GD');
insert into country(name_ca, name_en, name_es, code) values ('Geòrgia', 'Georgia', 'Georgia', 'GE');
insert into country(name_ca, name_en, name_es, code) values ('Guaiana Francesa', 'French Guiana', 'Guayana Francesa', 'GF');
insert into country(name_ca, name_en, name_es, code) values ('Guernsey', 'Guernsey', 'Guernsey', 'GG');
insert into country(name_ca, name_en, name_es, code) values ('Ghana', 'Ghana', 'Ghana', 'GH');
insert into country(name_ca, name_en, name_es, code) values ('Gibraltar', 'Gibraltar', 'Gibraltar', 'GI');
insert into country(name_ca, name_en, name_es, code) values ('Groenlàndia', 'Greenland', 'Groenlandia', 'GL');
insert into country(name_ca, name_en, name_es, code) values ('Gàmbia', 'Gambia', 'Gambia', 'GM');
insert into country(name_ca, name_en, name_es, code) values ('Guinea', 'Guinea', 'Guinea', 'GN');
insert into country(name_ca, name_en, name_es, code) values ('Guadalupe', 'Guadeloupe', 'Guadalupe', 'GP');
insert into country(name_ca, name_en, name_es, code) values ('Guinea Equatorial', 'Equatorial Guinea', 'Guinea Ecuatorial', 'GQ');
insert into country(name_ca, name_en, name_es, code) values ('Grècia', 'Greece', 'Grecia', 'GR');
insert into country(name_ca, name_en, name_es, code) values ('Illes Geòrgia del Sud i Sandwich del Sud', 'South Georgia and the South Sandwich Islands', 'Islas Georgias del Sur y Sandwich del Sur', 'GS');
insert into country(name_ca, name_en, name_es, code) values ('Guatemala', 'Guatemala', 'Guatemala', 'GT');
insert into country(name_ca, name_en, name_es, code) values ('Guam', 'Guam', 'Guam', 'GU');
insert into country(name_ca, name_en, name_es, code) values ('Guinea-Bissau', 'Guinea-Bissau', 'Guinea Bissau', 'GW');
insert into country(name_ca, name_en, name_es, code) values ('Guyana', 'Guyana', 'Guyana', 'GY');
insert into country(name_ca, name_en, name_es, code) values ('Hong Kong, Xina', 'Hong Kong', 'Hong Kong', 'HK');
insert into country(name_ca, name_en, name_es, code) values ('Illes Heard i McDonald', 'Heard Island and McDonald Islands', 'Isla Heard y McDonald', 'HM');
insert into country(name_ca, name_en, name_es, code) values ('Hondures', 'Honduras', 'Honduras', 'HN');
insert into country(name_ca, name_en, name_es, code) values ('Croàcia', 'Croatia', 'Croacia', 'HR');
insert into country(name_ca, name_en, name_es, code) values ('Haití', 'Haiti', 'Haití', 'HT');
insert into country(name_ca, name_en, name_es, code) values ('Hongria', 'Hungary', 'Hungría', 'HU');
insert into country(name_ca, name_en, name_es, code) values ('Indonèsia', 'Indonesia', 'Indonesia', 'ID');
insert into country(name_ca, name_en, name_es, code) values ('Irlanda', 'Ireland', 'Irlanda', 'IE');
insert into country(name_ca, name_en, name_es, code) values ('Israel', 'Israel', 'Israel', 'IL');
insert into country(name_ca, name_en, name_es, code) values ('Illa de Man', 'Isle of Man', 'Isla de Man', 'IM');
insert into country(name_ca, name_en, name_es, code) values ('Índia', 'India', 'India', 'IN');
insert into country(name_ca, name_en, name_es, code) values ('Territori Britànic de l''Oceà Índic', 'British Indian Ocean Territory', 'Territorio Británico del Océano Índico', 'IO');
insert into country(name_ca, name_en, name_es, code) values ('Iraq, l''', 'Iraq', 'Iraq', 'IQ');
insert into country(name_ca, name_en, name_es, code) values ('Iran', 'Iran', 'Irán', 'IR');
insert into country(name_ca, name_en, name_es, code) values ('Islàndia', 'Iceland', 'Islandia', 'IS');
insert into country(name_ca, name_en, name_es, code) values ('Itàlia', 'Italy', 'Italia', 'IT');
insert into country(name_ca, name_en, name_es, code) values ('Jersey', 'Jersey', 'Jersey', 'JE');
insert into country(name_ca, name_en, name_es, code) values ('Jamaica', 'Jamaica', 'Jamaica', 'JM');
insert into country(name_ca, name_en, name_es, code) values ('Jordània', 'Jordan', 'Jordania', 'JO');
insert into country(name_ca, name_en, name_es, code) values ('Japó', 'Japan', 'Japón', 'JP');
insert into country(name_ca, name_en, name_es, code) values ('Kenya', 'Kenya', 'Kenia', 'KE');
insert into country(name_ca, name_en, name_es, code) values ('Kirguizstan', 'Kyrgyzstan', 'Kirguistán', 'KG');
insert into country(name_ca, name_en, name_es, code) values ('Cambodja', 'Cambodia', 'Camboya', 'KH');
insert into country(name_ca, name_en, name_es, code) values ('Kiribati', 'Kiribati', 'Kiribati', 'KI');
insert into country(name_ca, name_en, name_es, code) values ('Comores, les', 'Comoros', 'Comoras', 'KM');
insert into country(name_ca, name_en, name_es, code) values ('Saint Kitts i Nevis', 'Saint Kitts and Nevis', 'San Cristobal y Nieves', 'KN');
insert into country(name_ca, name_en, name_es, code) values ('Corea del Nord', 'North Korea', 'Corea del Norte', 'KP');
insert into country(name_ca, name_en, name_es, code) values ('Corea del Sud', 'South Korea', 'Corea del Sur', 'KR');
insert into country(name_ca, name_en, name_es, code) values ('Kuwait', 'Kuwait', 'Kuwait', 'KW');
insert into country(name_ca, name_en, name_es, code) values ('Illes Caiman', 'Cayman Islands', 'Islas Caimán', 'KY');
insert into country(name_ca, name_en, name_es, code) values ('Kazakhstan', 'Kazakhstan', 'Kazajistán', 'KZ');
insert into country(name_ca, name_en, name_es, code) values ('Lao', 'Laos', 'Laos', 'LA');
insert into country(name_ca, name_en, name_es, code) values ('Líban', 'Lebanon', 'Líbano', 'LB');
insert into country(name_ca, name_en, name_es, code) values ('Saint Lucia', 'Saint Lucia', 'Santa Lucía', 'LC');
insert into country(name_ca, name_en, name_es, code) values ('Liechtenstein', 'Liechtenstein', 'Liechtenstein', 'LI');
insert into country(name_ca, name_en, name_es, code) values ('Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'LK');
insert into country(name_ca, name_en, name_es, code) values ('Libèria', 'Liberia', 'Liberia', 'LR');
insert into country(name_ca, name_en, name_es, code) values ('Lesotho', 'Lesotho', 'Lesotho', 'LS');
insert into country(name_ca, name_en, name_es, code) values ('Lituània', 'Lithuania', 'Lituania', 'LT');
insert into country(name_ca, name_en, name_es, code) values ('Luxemburg', 'Luxembourg', 'Luxemburgo', 'LU');
insert into country(name_ca, name_en, name_es, code) values ('Letònia', 'Latvia', 'Letonia', 'LV');
insert into country(name_ca, name_en, name_es, code) values ('Líbia', 'Libya', 'Libia', 'LY');
insert into country(name_ca, name_en, name_es, code) values ('Marroc, el', 'Morocco', 'Marruecos', 'MA');
insert into country(name_ca, name_en, name_es, code) values ('Mònaco', 'Monaco', 'Mónaco', 'MC');
insert into country(name_ca, name_en, name_es, code) values ('Moldàvia', 'Moldova', 'Moldavia', 'MD');
insert into country(name_ca, name_en, name_es, code) values ('Montenegro', 'Montenegro', 'Montenegro', 'ME');
insert into country(name_ca, name_en, name_es, code) values ('Saint-Martin', 'Saint Martin', 'San Martín', 'MF');
insert into country(name_ca, name_en, name_es, code) values ('Madagascar', 'Madagascar', 'Madagascar', 'MG');
insert into country(name_ca, name_en, name_es, code) values ('Illes Marshall', 'Marshall Islands', 'Islas Marshall', 'MH');
insert into country(name_ca, name_en, name_es, code) values ('Macedònia del Nord', 'Macedonia', 'Macedonia', 'MK');
insert into country(name_ca, name_en, name_es, code) values ('Mali', 'Mali', 'Malí', 'ML');
insert into country(name_ca, name_en, name_es, code) values ('Myanmar', 'Myanmar', 'Myanmar', 'MM');
insert into country(name_ca, name_en, name_es, code) values ('Mongòlia', 'Mongolia', 'Mongolia', 'MN');
insert into country(name_ca, name_en, name_es, code) values ('Macao, Xina', 'Macao', 'Macao', 'MO');
insert into country(name_ca, name_en, name_es, code) values ('Illes Marianes del Nord', 'Northern Mariana Islands', 'Islas Marianas del Norte', 'MP');
insert into country(name_ca, name_en, name_es, code) values ('Martinica', 'Martinique', 'Martinica', 'MQ');
insert into country(name_ca, name_en, name_es, code) values ('Mauritània', 'Mauritania', 'Mauritania', 'MR');
insert into country(name_ca, name_en, name_es, code) values ('Montserrat', 'Montserrat', 'Montserrat', 'MS');
insert into country(name_ca, name_en, name_es, code) values ('Malta', 'Malta', 'Malta', 'MT');
insert into country(name_ca, name_en, name_es, code) values ('Maurici', 'Mauritius', 'Mauricio', 'MU');
insert into country(name_ca, name_en, name_es, code) values ('Maldives', 'Maldives', 'Maldivas', 'MV');
insert into country(name_ca, name_en, name_es, code) values ('Malawi', 'Malawi', 'Malawi', 'MW');
insert into country(name_ca, name_en, name_es, code) values ('Mèxic', 'Mexico', 'México', 'MX');
insert into country(name_ca, name_en, name_es, code) values ('Malàisia', 'Malaysia', 'Malasia', 'MY');
insert into country(name_ca, name_en, name_es, code) values ('Moçambic', 'Mozambique', 'Mozambique', 'MZ');
insert into country(name_ca, name_en, name_es, code) values ('Namíbia', 'Namibia', 'Namibia', 'NA');
insert into country(name_ca, name_en, name_es, code) values ('Nova Caledònia', 'New Caledonia', 'Nueva Caledonia', 'NC');
insert into country(name_ca, name_en, name_es, code) values ('Níger', 'Niger', 'Niger', 'NE');
insert into country(name_ca, name_en, name_es, code) values ('Illa Norfolk', 'Norfolk Island', 'Isla Norfolk', 'NF');
insert into country(name_ca, name_en, name_es, code) values ('Nigèria', 'Nigeria', 'Nigeria', 'NG');
insert into country(name_ca, name_en, name_es, code) values ('Nicaragua', 'Nicaragua', 'Nicaragua', 'NI');
insert into country(name_ca, name_en, name_es, code) values ('Països Baixos', 'Netherlands', 'Países Bajos', 'NL');
insert into country(name_ca, name_en, name_es, code) values ('Noruega', 'Norway', 'Noruega', 'NO');
insert into country(name_ca, name_en, name_es, code) values ('Nepal', 'Nepal', 'Nepal', 'NP');
insert into country(name_ca, name_en, name_es, code) values ('Nauru', 'Nauru', 'Nauru', 'NR');
insert into country(name_ca, name_en, name_es, code) values ('Niue', 'Niue', 'Niue', 'NU');
insert into country(name_ca, name_en, name_es, code) values ('Nova Zelanda', 'New Zealand', 'Nueva Zelanda', 'NZ');
insert into country(name_ca, name_en, name_es, code) values ('Oman', 'Oman', 'Omán', 'OM');
insert into country(name_ca, name_en, name_es, code) values ('Panamà', 'Panama', 'Panamá', 'PA');
insert into country(name_ca, name_en, name_es, code) values ('Perú', 'Peru', 'Perú', 'PE');
insert into country(name_ca, name_en, name_es, code) values ('Polinèsia Francesa', 'French Polynesia', 'Polinesia Francesa', 'PF');
insert into country(name_ca, name_en, name_es, code) values ('Papua Nova Guinea', 'Papua New Guinea', 'Papúa Nueva Guinea', 'PG');
insert into country(name_ca, name_en, name_es, code) values ('Filipines', 'Philippines', 'Filipinas', 'PH');
insert into country(name_ca, name_en, name_es, code) values ('Pakistan', 'Pakistan', 'Pakistán', 'PK');
insert into country(name_ca, name_en, name_es, code) values ('Polònia', 'Poland', 'Polonia', 'PL');
insert into country(name_ca, name_en, name_es, code) values ('Saint-Pierre-et-Miquelon', 'Saint Pierre and Miquelon', 'San Pedro y Miquelón', 'PM');
insert into country(name_ca, name_en, name_es, code) values ('Pitcairn', 'Pitcairn', 'Islas Pitcairn', 'PN');
insert into country(name_ca, name_en, name_es, code) values ('Puerto Rico', 'Puerto Rico', 'Puerto Rico', 'PR');
insert into country(name_ca, name_en, name_es, code) values ('Palestina', 'Palestine', 'Palestina', 'PS');
insert into country(name_ca, name_en, name_es, code) values ('Portugal', 'Portugal', 'Portugal', 'PT');
insert into country(name_ca, name_en, name_es, code) values ('Palau', 'Palau', 'Palau', 'PW');
insert into country(name_ca, name_en, name_es, code) values ('Paraguai', 'Paraguay', 'Paraguay', 'PY');
insert into country(name_ca, name_en, name_es, code) values ('Qatar', 'Qatar', 'Catar', 'QA');
insert into country(name_ca, name_en, name_es, code) values ('Reunió, la', 'Réunion', 'Reunión', 'RE');
insert into country(name_ca, name_en, name_es, code) values ('Romania', 'Romania', 'Rumanía', 'RO');
insert into country(name_ca, name_en, name_es, code) values ('Sèrbia', 'Serbia', 'Serbia', 'RS');
insert into country(name_ca, name_en, name_es, code) values ('Rússia', 'Russian Federation', 'Rusia', 'RU');
insert into country(name_ca, name_en, name_es, code) values ('Ruanda', 'Rwanda', 'Ruanda', 'RW');
insert into country(name_ca, name_en, name_es, code) values ('Aràbia Saudí', 'Saudi Arabia', 'Arabia Saudita', 'SA');
insert into country(name_ca, name_en, name_es, code) values ('Illes Salomó', 'Solomon Islands', 'Islas Salomón', 'SB');
insert into country(name_ca, name_en, name_es, code) values ('Seychelles', 'Seychelles', 'Seychelles', 'SC');
insert into country(name_ca, name_en, name_es, code) values ('Sudan, el', 'Sudan', 'Sudán', 'SD');
insert into country(name_ca, name_en, name_es, code) values ('Suècia', 'Sweden', 'Suecia', 'SE');
insert into country(name_ca, name_en, name_es, code) values ('Singapur', 'Singapore', 'Singapur', 'SG');
insert into country(name_ca, name_en, name_es, code) values ('Saint Helena, Ascenció i Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha', 'Santa Elena, Ascensión y Tristán de Acuña', 'SH');
insert into country(name_ca, name_en, name_es, code) values ('Eslovènia', 'Slovenia', 'Eslovenia', 'SI');
insert into country(name_ca, name_en, name_es, code) values ('Svalbard i Jan Mayen', 'Svalbard and Jan Mayen', 'Svalbard y Jan Mayen', 'SJ');
insert into country(name_ca, name_en, name_es, code) values ('Eslovàquia', 'Slovakia', 'Eslovaquia', 'SK');
insert into country(name_ca, name_en, name_es, code) values ('Sierra Leone', 'Sierra Leone', 'Sierra Leona', 'SL');
insert into country(name_ca, name_en, name_es, code) values ('San Marino', 'San Marino', 'San Marino', 'SM');
insert into country(name_ca, name_en, name_es, code) values ('Senegal', 'Senegal', 'Senegal', 'SN');
insert into country(name_ca, name_en, name_es, code) values ('Somàlia', 'Somalia', 'Somalia', 'SO');
insert into country(name_ca, name_en, name_es, code) values ('Surinam', 'Suriname', 'Surinam', 'SR');
insert into country(name_ca, name_en, name_es, code) values ('Sudan del Sud, el', 'South Sudan', 'Sudán del Sur', 'SS');
insert into country(name_ca, name_en, name_es, code) values ('São Tomé i Príncipe', 'Sao Tome and Principe', 'Santo Tomé y Príncipe', 'ST');
insert into country(name_ca, name_en, name_es, code) values ('El Salvador', 'El Salvador', 'El Salvador', 'SV');
insert into country(name_ca, name_en, name_es, code) values ('Sint Maarten', 'Sint Maarten', 'Sint Maarten', 'SX');
insert into country(name_ca, name_en, name_es, code) values ('Síria', 'Syrian Arab Republic', 'Siria', 'SY');
insert into country(name_ca, name_en, name_es, code) values ('Eswatini', 'Eswatini', 'Suazilandia', 'SZ');
insert into country(name_ca, name_en, name_es, code) values ('Illes Turks i Caicos', 'Turks and Caicos Islands', 'Islas Turcas y Caicos', 'TC');
insert into country(name_ca, name_en, name_es, code) values ('Txad', 'Chad', 'Chad', 'TD');
insert into country(name_ca, name_en, name_es, code) values ('Terres Australs i Antàrtiques Franceses', 'French Southern Territories', 'Tierras Australes y Antárticas Francesas', 'TF');
insert into country(name_ca, name_en, name_es, code) values ('Togo', 'Togo', 'Togo', 'TG');
insert into country(name_ca, name_en, name_es, code) values ('Tailàndia', 'Thailand', 'Tailandia', 'TH');
insert into country(name_ca, name_en, name_es, code) values ('Tadjikistan', 'Tajikistan', 'Tayikistan', 'TJ');
insert into country(name_ca, name_en, name_es, code) values ('Tokelau', 'Tokelau', 'Tokelau', 'TK');
insert into country(name_ca, name_en, name_es, code) values ('Timor-Leste', 'Timor-Leste', 'Timor-Leste', 'TL');
insert into country(name_ca, name_en, name_es, code) values ('Turkmenistan', 'Turkmenistan', 'Turkmenistán', 'TM');
insert into country(name_ca, name_en, name_es, code) values ('Tunísia', 'Tunisia', 'Túnez', 'TN');
insert into country(name_ca, name_en, name_es, code) values ('Tonga', 'Tonga', 'Tonga', 'TO');
insert into country(name_ca, name_en, name_es, code) values ('Turquia', 'Turkey', 'Turquía', 'TR');
insert into country(name_ca, name_en, name_es, code) values ('Trinidad i Tobago', 'Trinidad and Tobago', 'Trinidad y Tobago', 'TT');
insert into country(name_ca, name_en, name_es, code) values ('Tuvalu', 'Tuvalu', 'Tuvalu', 'TV');
insert into country(name_ca, name_en, name_es, code) values ('Taiwan', 'Taiwan', 'Taiwan', 'TW');
insert into country(name_ca, name_en, name_es, code) values ('Tanzània', 'Tanzania', 'Tanzania', 'TZ');
insert into country(name_ca, name_en, name_es, code) values ('Ucraïna', 'Ukraine', 'Ucrania', 'UA');
insert into country(name_ca, name_en, name_es, code) values ('Uganda', 'Uganda', 'Uganda', 'UG');
insert into country(name_ca, name_en, name_es, code) values ('Illes Menors Allunyades dels Estats Units', 'United States Minor Outlying Islands', 'Islas Ultramarinas Menores de Estados Unidos', 'UM');
insert into country(name_ca, name_en, name_es, code) values ('Estats Units, els', 'United States', 'Estados Unidos', 'US');
insert into country(name_ca, name_en, name_es, code) values ('Uruguai', 'Uruguay', 'Uruguay', 'UY');
insert into country(name_ca, name_en, name_es, code) values ('Uzbekistan', 'Uzbekistan', 'Uzbekistán', 'UZ');
insert into country(name_ca, name_en, name_es, code) values ('Santa Seu', 'Holy See (Vatican City State)', 'Vaticano, Ciudad del', 'VA');
insert into country(name_ca, name_en, name_es, code) values ('Saint Vincent i les Grenadines', 'Saint Vincent and the Grenadines', 'San Vicente y las Granadinas', 'VC');
insert into country(name_ca, name_en, name_es, code) values ('Veneçuela', 'Venezuela, Bolivarian Republic of', 'Venezuela', 'VE');
insert into country(name_ca, name_en, name_es, code) values ('Illes Verges Britàniques', 'Virgin Islands, British', 'Islas Vírgenes Británicas', 'VG');
insert into country(name_ca, name_en, name_es, code) values ('Illes Verges dels Estats Units', 'Virgin Islands, U.S.', 'Islas Vírgenes de los Estados Unidos', 'VI');
insert into country(name_ca, name_en, name_es, code) values ('Vietnam', 'Viet Nam', 'Vietnam', 'VN');
insert into country(name_ca, name_en, name_es, code) values ('Vanuatu', 'Vanuatu', 'Vanuatu', 'VU');
insert into country(name_ca, name_en, name_es, code) values ('Wallis i Futuna', 'Wallis and Futuna', 'Wallis y Futuna', 'WF');
insert into country(name_ca, name_en, name_es, code) values ('Samoa', 'Samoa', 'Samoa', 'WS');
insert into country(name_ca, name_en, name_es, code) values ('Iemen, el', 'Yemen', 'Yemen', 'YE');
insert into country(name_ca, name_en, name_es, code) values ('Mayotte', 'Mayotte', 'Mayotte', 'YT');
insert into country(name_ca, name_en, name_es, code) values ('Sud-àfrica', 'South Africa', 'Sudáfrica', 'ZA');
insert into country(name_ca, name_en, name_es, code) values ('Zàmbia', 'Zambia', 'Zambia', 'ZM');
insert into country(name_ca, name_en, name_es, code) values ('Zimbàbue', 'Zimbabwe', 'Zimbabue', 'ZW');
